missing CancellationToken implemented
dotnetcore/EasyCaching pull request #389
Opened 2022-08-02 12:43 UTC by st0o0

Hello

For a project of mine I needed a cache.
This library does everything I need and more.

I want to use the async functions.
There was missing for me the optional CancellationToken.
This is always quite handy.

I noticed during the implementation that not all providers support this.

Nevertheless, I added it everywhere in the function header and where the provider supported it also passed it.

I hope this "fix" or whatever comes in the next version.

Thanks a lot!

2022-08-02 16:46 UTC, st0o0 commented
Oh should I fix the errors?

have adjusted the IEasyCachingProvider therefore the errors come very likely.

2022-08-03 13:59 UTC, catcherwong requested changes

2022-08-03 13:59 UTC, catcherwong commented on src/EasyCaching.HybridCache/HybridCachingProvider.cs
> +        /// <param name="cancellationToken">CancellationToken</param>
XML comment has a param tag for 'cancellationToken', but there is no parameter by that name

2022-08-04 01:00 UTC, catcherwong approved these changes
LGTM

2022-08-04 01:00 UTC, merged