whether can support zookeeper bus and kafka bus #404
dotnetcore/EasyCaching pull request #405
Opened 2022-10-11 09:12 UTC by bingtianyiyan

fix： #404 whether can support zookeeper bus and kafka bus

2022-10-13 14:58 UTC, catcherwong requested changes

2022-10-13 14:58 UTC, catcherwong commented on sample/EasyCaching.Demo.Providers/Startup.cs
> +                    config.DBConfig.Endpoints.Add(new ServerEndPoint("192.168.99.100", 6379));
maybe should not modify the endpoint of the sample.

2022-10-13 14:58 UTC, catcherwong commented on bus/EasyCaching.Bus.Zookeeper/EasyCaching.Bus.Zookeeper.csproj
> +		<VersionPrefix>$(EasyCachingZookeeperBusPackageVersion)</VersionPrefix>
Should add this in `build/version.props`.

2022-10-13 14:58 UTC, catcherwong commented on bus/EasyCaching.Bus.Zookeeper/EasyCaching.Bus.Zookeeper.csproj
> +			$(EasyCachingKafkaBusPackageNotes)
Should add this in `build/releasenotes.props`.

2022-10-13 14:58 UTC, catcherwong commented on bus/EasyCaching.Bus.ConfluentKafka/EasyCaching.Bus.ConfluentKafka.csproj
> +		<VersionPrefix>$(EasyCachingKafkaBusPackageVersion)</VersionPrefix>
Should add this in `build/version.props`.

2022-10-13 14:58 UTC, catcherwong commented on bus/EasyCaching.Bus.ConfluentKafka/EasyCaching.Bus.ConfluentKafka.csproj
> +			$(EasyCachingKafkaBusPackageNotes)
Should add this in `build/releasenotes.props`.

2022-10-18 09:10 UTC, catcherwong commented
Please resolve conflicts.

2022-10-18 10:29 UTC, bingtianyiyan commented
> Please resolve conflicts.

have been resloved conflicts

2022-10-18 10:58 UTC, catcherwong approved these changes

2022-10-18 10:59 UTC, merged